Repository ipsilon/evmone, pull requests merged in 2024-03, with the labels that each got.

#824 state: Fix failing code deployment in Frontier
  test/state/host.cpp
  test/unittests/state_transition_create_test.cpp
Labels: bug

#587 host: Make EOF opaque for EXTCODE* instructions
  circle.yml
  test/state/host.cpp
  test/unittests/CMakeLists.txt
  test/unittests/state_transition_extcode_test.cpp
Labels: EOF

#837 test: Improve error of invalid hash in JSON
  test/statetest/statetest_loader.cpp
  test/unittests/statetest_loader_tx_test.cpp
Labels: tests

#838 t8n: System contracts execution and other improvements
  test/integration/CMakeLists.txt
  test/integration/t8n/CMakeLists.txt
  test/integration/t8n/cancun_create_tx/alloc.json
  test/integration/t8n/cancun_create_tx/env.json
  test/integration/t8n/cancun_create_tx/txs.json
  test/t8n/t8n.cpp
Labels: tests

#842 RLP-encode invalid transactions
  test/integration/t8n/CMakeLists.txt
  test/integration/t8n/cancun_create_tx/txs.json
  test/state/state.cpp
  test/unittests/state_rlp_test.cpp
Labels: tests

#848 ci: Upgrade spec tests
  circle.yml
Labels: tests

#836 Move EOF creation transition tests to separate file
  test/unittests/CMakeLists.txt
  test/unittests/state_transition_create_test.cpp
  test/unittests/state_transition_eof_create_test.cpp
Labels: EOF
