Repository ipsilon/evmone, pull requests merged in 2025-01, with the labels that each got.

#1097 eof: Improve `has_full_data()` helper
  lib/evmone/eof.hpp
Labels: EOF

#1100 test: Generate default comparison operator for CodeParams
  test/bench/synthetic_benchmarks.cpp
Labels: tests

#1077 EIP-4844 - pass blockchain tests
  circle.yml
  test/blockchaintest/blockchaintest.hpp
  test/blockchaintest/blockchaintest_loader.cpp
  test/blockchaintest/blockchaintest_runner.cpp
  test/state/block.cpp
  test/state/block.hpp
  test/state/host.cpp
  test/state/state.cpp
  test/state/transaction.hpp
  test/statetest/statetest_loader.cpp
  test/t8n/t8n.cpp
  test/unittests/state_transition.cpp
  test/unittests/state_transition_block_test.cpp
  test/unittests/state_transition_tx_test.cpp
  test/unittests/state_tx_test.cpp
Labels: Cancun

#1107 test: Add basic smoke tests for tx data cost
  test/unittests/state_tx_test.cpp
Labels: tests

#1095 Implement EIP-7623 "Increase calldata cost"
  circle.yml
  test/state/state.cpp
  test/state/transaction.hpp
  test/statetest/statetest_runner.cpp
  test/unittests/state_transition_tx_test.cpp
  test/unittests/state_tx_test.cpp
Labels: Prague

#1089 Updates to BLS precompiles (EIP-2537)
  circle.yml
  test/state/precompiles.cpp
  test/state/precompiles.hpp
  test/state/precompiles_internal.hpp
  test/unittests/state_precompiles_test.cpp
Labels: precompiles, Prague

#1093 Update Blockhash History system contract address (EIP-2935)
  circle.yml
  test/state/system_contracts.hpp
Labels: Prague

#1094 Exclude empty requests data in commitment (EIP-7685)
  circle.yml
  test/integration/t8n/CMakeLists.txt
  test/state/requests.cpp
  test/t8n/t8n.cpp
Labels: Prague

#1112 Update system contract addresses according to latest spec
  circle.yml
  test/state/system_contracts.hpp
Labels: Prague

#1115 ci: Upgrade EEST pectra-devnet-5 tests
  circle.yml
Labels: Prague

#918 ci: Build clang/sanitizers with debug libc++
  circle.yml
  cmake/toolchains/clang-libcxx-debug.cmake
Labels: tests
